### ISSUE TITLE
OOP library schrijven

### ISSUE THREAD

**Issue by maniflames** [sven-zo/virtuvis#17]
Op de server gaat er gewerkt worden met OOP, de 'library' die we nodig hebben moet wel nog geschreven worden. 

Het gaat om de volgende klassen:
- [x] database
- [x] user
- [x] api
- [x] wiki (extends api)
- [x] wheater (extends keySecuredApi)
- [x] fish

**Comment by sven-zo** [comment]
Goed bezig! 👍
